[2024-10-02 23:24:32,902] ERROR log_exception() L838  Exception on /cliente [POST] - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\back-end\app.py", line 65, in predict
    X_input = PreProcessador.preparar_form(form)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\back-end\model\preprocessador.py", line 48, in preparar_form
    x_input = x_input.reshape(1, -1)
              ^^^^^^^
UnboundLocalError: cannot access local variable 'x_input' where it is not associated with a value
[2024-10-02 23:24:32,919] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:24:32] "[35m[1mPOST /cliente HTTP/1.1[0m" 500 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:25:18,374] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.12:5000 - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:25:18,374] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:25:35,160] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:25:35] "GET /clientes?nome=Laryssa HTTP/1.1" 200 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:25:36,495] WARNING predict() L122  Erro ao adicionar cliente 'Laryssa', Não foi possível salvar novo item :/ - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\back-end\app.py L122 
[2024-10-02 23:25:36,496] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:25:36] "[31m[1mPOST /cliente HTTP/1.1[0m" 400 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:31:51,719] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.12:5000 - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:31:51,735] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:32:17,974] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:32:17] "GET /clientes?nome=Mica HTTP/1.1" 200 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:32:19,350] WARNING predict() L136  Erro ao adicionar cliente 'Mica', Não foi possível salvar novo item :/ - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\back-end\app.py L136 
[2024-10-02 23:32:19,350] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:32:19] "[31m[1mPOST /cliente HTTP/1.1[0m" 400 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:45:48,705] INFO _log() L97   [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.12:5000 - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:45:48,716] INFO _log() L97   [33mPress CTRL+C to quit[0m - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:46:11,151] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:46:11] "GET /clientes?nome=Iury HTTP/1.1" 200 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
[2024-10-02 23:46:11,168] ERROR log_exception() L838  Exception on /cliente [POST] - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py L838 
Traceback (most recent call last):
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\flask_openapi3\scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\back-end\app.py", line 65, in predict
    x_input = PreProcessador.preparar_form(form)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\back-end\model\preprocessador.py", line 36, in preparar_form
    gender_Female = int(form.gender == 0)
                        ^^^^^^^^^^^
  File "C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\pydantic\main.py", line 856, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'ClienteSchema' object has no attribute 'gender'
[2024-10-02 23:46:11,176] INFO _log() L97   127.0.0.1 - - [02/Oct/2024 23:46:11] "[35m[1mPOST /cliente HTTP/1.1[0m" 500 - - call_trace=C:\Users\Notbook\Desktop\PUC\Eng. Software\MVP\MVP - Qualidade de Software e Sistemas Inteligentes\env\Lib\site-packages\werkzeug\_internal.py L97  
